### ISSUE TITLE
Can not build project because of Type error: Property 'model' does not exist on type 'Object Definition Block'

### ISSUE THREAD

**Issue by hongduc-phan** [hexrcs/fullstack-graphql-next-nexus-prisma#4]
I tried to build project by running yarn build but get the error: Type error: Property 'model' does not exist on type 'Object Definition Block'

I run yarn dev and it works
Please help me .

**Comment by hexrcs** [comment]
Hey Harry!

I'm actually unable to reproduce this issue with Yarn `v1.22.4`, both with this boilerplate repo and [your E-Commerce project](https://github.com/hongduc-phan/E-commerce-webApp). Which Yarn version are you currently on? Are you using Yarn 2?

You mentioned in our correspondence that you were using `next build` as the `build` command. We are required to run `nexus build` command in order to generate the Nexus GraphQL server (based on the schema) before Next.js can use it in the `/api/graphql` route. This means we need to run `nexus build` first before running `next build` (or all in one command, `nexus build && next build`).

Let me know if this clears things up. :)
